### ISSUE TITLE
Dedicated thread for new connections.

### ISSUE THREAD

**Issue by nitrix** [alexleclair/GameNgine#1]
I think until the player gets logged in game, it should be assigned to a thread so it can authenticate, query a database, load its data in memory then the Session handle is moved to a Client instance that register with the ACE_Reactor for future incoming packets and be handled normally (asynchronously, one by one).

This simple procedure prevents everyone from a short lag when someone is joining and the server has to query the database and wait for an answer to continue.

But, it adds a new problem: creating threads on the fly is costly, we'll need some sort of ThreadPool.

Delicate piece of code, but I'm willing to do it since @stax0160 is only starting his work on the Client next week.

**Comment by alexleclair** [comment]
Jusssssst going to close this 8 year old issue as `will not fix` 😬
